export const blogs = [
    {
        id: "01",
        blogName: "Blog 1",
        blogImage: "/images/accessories-519693_1920.jpg",
        blogImage1: "/images/amethyst-2186842_1920.jpg",
        blogImage2: "/images/apatite-669515_1920.jpg",
        author: "John",
        authorImage: "/images/profile3.jpg",
        date: "07 August, 2022",
        category: "food",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
        
    },
    {
        id: "02",
        blogName: "Blog 2",
        blogImage: "/images/diamond-2186840_1920.jpg",
        blogImage1: "/images/gold-3184582_1920.jpg",
        blogImage2: "/images/chain-784422_1920.jpg",
        author: "Alice",
        authorImage: "/images/profile1.jpg",
        date: "15 January, 2021",
        category: "lifestyle",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "03",
        blogName: "Blog 3",
        blogImage: "/images/earrings-852900_1920.jpg",
        blogImage1: "/images/wedding-rings-3611277_1920.jpg",
        blogImage2: "/images/wedding-1594957_1920.jpg",
        author: "Emily",
        authorImage: "/images/profile2.jpg",
        date: "23 March, 2020",
        category: "travel",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "04",
        blogName: "Blog 4",
        blogImage: "/images/amethyst-2186842_1920.jpg",
        blogImage1: "/images/apatite-669515_1920.jpg",
        blogImage2: "/images/chain-784422_1920.jpg",
        author: "Robert",
        authorImage: "/images/profile4.jpg",
        date: "09 November, 2022",
        category: "adventure",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "05",
        blogName: "Blog 5",
        blogImage: "/images/gold-jewelry-3790542_1920.jpg",
        blogImage1: "/images/img-1.jpg",
        blogImage2: "/images/img-2.jpg",
        author: "Laura",
        authorImage: "/images/profile5.jpg",
        date: "02 June, 2023",
        category: "business",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "06",
        blogName: "Blog 6",
        blogImage: "/images/woman-1149909_1920.jpg",
        blogImage1: "/images/woman-1149911_1920.jpg",
        blogImage2: "/images/apatite-669515_1920.jpg",
        author: "James",
        authorImage: "/images/profile6.jpg",
        date: "18 February, 2021",
        category: "food",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "07",
        blogName: "Blog 7",
        blogImage: "/images/amethyst-2186842_1920.jpg",
        blogImage1: "/images/chain-784422_1920.jpg",
        blogImage2: "/images/diamond-2186840_1920.jpg",
        author: "Sophia",
        authorImage: "/images/profile7.jpg",
        date: "30 April, 2020",
        category: "lifestyle",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "08",
        blogName: "Blog 8",
        blogImage: "/images/engagement-ring-2093824_1920.jpg",
        blogImage1: "/images/gold-3184582_1920.jpg",
        blogImage2: "/images/img-4.jpg",
        author: "Daniel",
        authorImage: "/images/profile8.jpg",
        date: "25 August, 2022",
        category: "travel",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "09",
        blogName: "Blog 9",
        blogImage: "/images/img-2.jpg",
        blogImage1: "/images/wedding-1594957_1920.jpg",
        blogImage2: "/images/earrings-852900_1920.jpg",
        author: "Olivia",
        authorImage: "/images/profile1.jpg",
        date: "16 March, 2021",
        category: "adventure",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "10",
        blogName: "Blog 10",
        blogImage: "/images/woman-518275_1920.jpg",
        blogImage1: "/images/img-7.jpg",
        blogImage2: "/images/diamond-2186840_1920.jpg",
        author: "Liam",
        authorImage: "/images/profile2.jpg",
        date: "14 July, 2020",
        category: "business",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "11",
        blogName: "Blog 11",
        blogImage: "/images/chain-784422_1920.jpg",
        blogImage1: "/images/gold-jewelry-3790542_1920.jpg",
        blogImage2: "/images/img-1.jpg",
        author: "Emma",
        authorImage: "/images/profile3.jpg",
        date: "11 September, 2022",
        category: "food",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "12",
        blogName: "Blog 12",
        blogImage: "/images/engagement-ring-2093824_1920.jpg",
        blogImage1: "/images/amethyst-2186842_1920.jpg",
        blogImage2: "/images/wedding-rings-3611277_1920.jpg",
        author: "Noah",
        authorImage: "/images/profile4.jpg",
        date: "27 December, 2021",
        category: "lifestyle",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "13",
        blogName: "Blog 13",
        blogImage: "/images/earrings-852900_1920.jpg",
        blogImage1: "/images/gold-3184582_1920.jpg",
        blogImage2: "/images/woman-1149909_1920.jpg",
        author: "Ava",
        authorImage: "/images/profile5.jpg",
        date: "19 October, 2020",
        category: "travel",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "14",
        blogName: "Blog 14",
        blogImage: "/images/amethyst-2186842_1920.jpg",
        blogImage1: "/images/diamond-2186840_1920.jpg",
        blogImage2: "/images/wedding-1594957_1920.jpg",
        author: "Ethan",
        authorImage: "/images/profile6.jpg",
        date: "05 November, 2022",
        category: "adventure",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "15",
        blogName: "Blog 15",
        blogImage: "/images/img-9.jpg",
        blogImage1: "/images/woman-518275_1920.jpg",
        blogImage2: "/images/chain-784422_1920.jpg",
        author: "Mia",
        authorImage: "/images/profile7.jpg",
        date: "22 January, 2023",
        category: "business",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "16",
        blogName: "Blog 16",
        blogImage: "/images/gold-jewelry-3790542_1920.jpg",
        blogImage1: "/images/engagement-ring-2093824_1920.jpg",
        blogImage2: "/images/img-4.jpg",
        author: "Oliver",
        authorImage: "/images/profile8.jpg",
        date: "30 June, 2020",
        category: "food",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "17",
        blogName: "Blog 17",
        blogImage: "/images/wedding-rings-3611277_1920.jpg",
        blogImage1: "/images/woman-1149911_1920.jpg",
        blogImage2: "/images/diamond-2186840_1920.jpg",
        author: "Isabella",
        authorImage: "/images/profile1.jpg",
        date: "14 March, 2021",
        category: "lifestyle",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    },
    {
        id: "18",
        blogName: "Blog 18",
        blogImage: "/images/apatite-669515_1920.jpg",
        blogImage1: "/images/gold-3184582_1920.jpg",
        blogImage2: "/images/img-7.jpg",
        author: "Lucas",
        authorImage: "/images/profile2.jpg",
        date: "11 May, 2022",
        category: "travel",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, libero.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus itaque odit iste veritatis quos dolor architecto soluta pariatur aliquam necessitatibus, dignissimos, esse reprehenderit odio consectetur. Voluptates repellendus labore iure odio. Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro deleniti voluptate doloribus tempora ad incidunt aperiam accusantium sed quaerat dolores neque deserunt nemo itaque assumenda asperiores labore a fuga ratione quae, voluptatibus ducimus atque cum tempore. Magni mollitia iure voluptate recusandae eum deserunt praesentium ex. Laudantium dolorum cumque rem ut facere mollitia, nemo praesentium culpa repudiandae quis modi quidem illum quisquam iste blanditiis at omnis fuga, iure necessitatibus enim repellat. Quidem rerum ipsam maxime, ipsum, beatae consectetur nobis quisquam nam asperiores hic nostrum. Error tempora qui, ad maxime facere autem nulla sint dolorum quis temporibus pariatur nisi deleniti. Ipsum, et.",
        brief: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias minus voluptatum aspernatur qui, totam eos facere asperiores accusamus sint ab numquam dignissimos praesentium culpa, quis perspiciatis nulla natus maxime quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique obcaecati iure illum quam accusantium nisi illo, ab natus quidem nihil facere vitae et. Error aut atque animi nihil, doloribus tenetur. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In sed odit fugiat voluptatibus debitis earum, corporis similique nobis quam reprehenderit suscipit quia non, voluptatem ex hic architecto eum, accusamus deleniti."
    }
]

