export const details = [
    {
        sku: "AX-0000153",
        name: "Diamond Ring",
        image1: "/images/img-5.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-7.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2500",
        costPrice: "3300",
        unit: "10",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000154",
        name: "Elegant Earrings",
        image1: "/images/img-11.jpg",
        image2: "/images/img-2.jpg",
        image3: "/images/img-12.jpg",
        image4: "/images/img-13.jpg",
        sellingPrice: "2200",
        costPrice: "3000",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000155",
        name: "Stylish Earrings",
        image1: "/images/earrings-852900_1920.jpg",
        image2: "/images/img-4.jpg",
        image3: "/images/img-7.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2000",
        costPrice: "2800",
        unit:"8",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000156",
        name: "Engagement Ring",
        image1: "/images/engagement-ring-2093824_1920.jpg",
        image2: "/images/img-5.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-7.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"0",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000157",
        name: "Gold Bracelet",
        image1: "/images/gold-3184582_1920.jpg",
        image2: "/images/img-8.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-4.jpg",
        sellingPrice: "2400",
        costPrice: "3200",
        unit:"2",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000158",
        name: "Luxury Pendant",
        image1: "/images/gold-jewelry-3790542_1920.jpg",
        image2: "/images/img-5.jpg",
        image3: "/images/img-8.jpg",
        image4: "/images/img-12.jpg",
        sellingPrice: "2600",
        costPrice: "3400",
        unit:"7",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000159",
        name: "Gold Ring",
        image1: "/images/img-4.jpg",
        image2: "/images/img-5.jpg",
        image3: "/images/img-7.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2300",
        costPrice: "3100",
        unit:"9",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000160",
        name: "Classic Bracelet",
        image1: "/images/img-6.jpg",
        image2: "/images/img-7.jpg",
        image3: "/images/img-8.jpg",
        image4: "/images/img-11.jpg",
        sellingPrice: "2500",
        costPrice: "3300",
        unit:"12",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000161",
        name: "Elegant Ring",
        image1: "/images/wedding-812967_1920.jpg",
        image2: "/images/wedding-rings-3611277_1920.jpg",
        image3: "/images/wedding-3369645_1920.jpg",
        image4: "/images/img-12.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"3",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000162",
        name: "Gold Pendant",
        image1: "/images/img-8.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-4.jpg",
        image4: "/images/img-11.jpg",
        sellingPrice: "2300",
        costPrice: "3100",
        unit:"3",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000163",
        name: "Silver Ring",
        image1: "/images/img-12.jpg",
        image2: "/images/img-5.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-13.jpg",
        sellingPrice: "2000",
        costPrice: "2800",
        unit:"10",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000164",
        name: "Elegant Pendant",
        image1: "/images/img-12.jpg",
        image2: "/images/img-8.jpg",
        image3: "/images/img-5.jpg",
        image4: "/images/img-6.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"10",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000165",
        name: "Silver Pendant",
        image1: "/images/img-11.jpg",
        image2: "/images/img-13.jpg",
        image3: "/images/img-12.jpg",
        image4: "/images/img-4.jpg",
        sellingPrice: "2400",
        costPrice: "3200",
        unit:"10",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000166",
        name: "Diamond Earrings",
        image1: "/images/img-2.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-7.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2500",
        costPrice: "3300",
        unit:"9",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000167",
        name: "Classic Ring",
        image1: "/images/img-5.jpg",
        image2: "/images/img-7.jpg",
        image3: "/images/img-4.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2600",
        costPrice: "3400",
        unit:"9",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000168",
        name: "Gold Necklace",
        image1: "/images/img-8.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-12.jpg",
        image4: "/images/img-11.jpg",
        sellingPrice: "2800",
        costPrice: "3600",
        unit:"9",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000169",
        name: "Platinum Earrings",
        image1: "/images/img-13.jpg",
        image2: "/images/img-4.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-12.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"9",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000170",
        name: "Elegant Pendant",
        image1: "/images/img-11.jpg",
        image2: "/images/img-8.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-7.jpg",
        sellingPrice: "2300",
        costPrice: "3100",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000171",
        name: "Gold Bracelet",
        image1: "/images/img-5.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-7.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2500",
        costPrice: "3300",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000172",
        name: "Stylish Necklace",
        image1: "/images/img-4.jpg",
        image2: "/images/img-12.jpg",
        image3: "/images/img-8.jpg",
        image4: "/images/img-7.jpg",
        sellingPrice: "2400",
        costPrice: "3200",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000173",
        name: "Luxury Earrings",
        image1: "/images/img-11.jpg",
        image2: "/images/img-13.jpg",
        image3: "/images/img-5.jpg",
        image4: "/images/img-6.jpg",
        sellingPrice: "2500",
        costPrice: "3300",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000174",
        name: "Classic Pendant",
        image1: "/images/img-12.jpg",
        image2: "/images/img-4.jpg",
        image3: "/images/img-5.jpg",
        image4: "/images/img-7.jpg",
        sellingPrice: "2600",
        costPrice: "3400",
        unit:"14",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000175",
        name: "Silver Bracelet",
        image1: "/images/img-13.jpg",
        image2: "/images/img-6.jpg",
        image3: "/images/img-8.jpg",
        image4: "/images/img-11.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"14",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000176",
        name: "Diamond Pendant",
        image1: "/images/img-7.jpg",
        image2: "/images/img-4.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-8.jpg",
        sellingPrice: "2400",
        costPrice: "3200",
        unit:"14",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000177",
        name: "Platinum Ring",
        image1: "/images/img-5.jpg",
        image2: "/images/img-8.jpg",
        image3: "/images/img-6.jpg",
        image4: "/images/img-7.jpg",
        sellingPrice: "2700",
        costPrice: "3500",
        unit:"0",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    },
    {
        sku: "AX-0000178",
        name: "Cosmic Earrings",
        image1: "/images/img-11.jpg",
        image2: "/images/img-2.jpg",
        image3: "/images/img-12.jpg",
        image4: "/images/img-13.jpg",
        sellingPrice: "2200",
        costPrice: "3600",
        unit:"4",
        brief:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi repellendus dicta repellat saepe molestiae et delectus tempora vitae quis quas. At cum in earum neque, incidunt iure architecto dolores laboriosam. Lorem ipsum.",
        details:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut dolore tempore nemo ullam at odio, aliquid rem dolor exercitationem architecto facilis suscipit doloribus, repudiandae ad necessitatibus, tempora perspiciatis inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi repudiandae enim eligendi modi commodi suscipit, itaque velit optio sequi! Iusto, unde delectus fugit reiciendis praesentium quaerat nulla fuga minima distinctio sit omnis. Nisi, nostrum. Magnam repellat maiores doloremque."
    }
];


